# The crawler config
crawler:
  host: "https://wptavern.com"
  apiPath: "wp-json/wp/v2/posts"
  perPage: 10

# The scheduler config
scheduler:
  intervalInSec: 20 # wordpress crawler will wake up every intervalInSec, if feasible
  startDateGmt: "2023-01-01T00:00:00Z" # wordpress crawler will load posts starting from this date
  maxCoolDownScale: 3

# The websocket config
websocket:
  port: 8888
  subscribePath: "ws://localhost:${port}/subscribe/v1"
